name: Build 3DS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSA3DS
          path: |
            *.3dsx
            *.elf
